version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: api_service
    ports:
      - "8888:8888"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: pass123
      DB_NAME: final
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: final
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
